title: Assemblage
description: A dataset (and tool for building) binary executable corpora.
url: https://assemblage-dataset.net
logo: /assets/images/logo.jpeg
theme: jekyll-theme-architect
google_analytics:
twitter:
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo.jpeg
